version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./html:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    build: ./php-fpm
    container_name: php-fpm-container
    volumes:
      - ./html:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
